### ISSUE TITLE
Private Method Case

### ISSUE THREAD

**Issue by bniewo** [nhemmings/Edge-Image-Cache-Utility#10]
VS is bitching about the case we are using on private methods. I have been writing them in camelCase similar to private variables. Do we want to switch it to MixedCase with a preceding underscore? for example checkCacheExists() would be renamed to _CheckCacheExists(). From what I can find this is how it is implemented in C++ and is how Microsoft prefers its naming scheme.

**Comment by nhemmings** [comment]
The thing I don't get is why it bitches about the UI methods that IT creates.

The preceding underscore and MixedCase is for private methods specifically?

**Comment by bniewo** [comment]
No clue probably because Microsoft is stupid. From what I could find the preceding underscore and mixed case is only for private methods. I did a few Google searches and that's what I could find

**Comment by nhemmings** [comment]
Do eet.

**Comment by bniewo** [comment]
I'll make the changes, do some code cleanup and commenting hopefully this afternoon and push the changes
