### ISSUE TITLE
Detect and notify of nested caches

### ISSUE THREAD

**Issue by nhemmings** [nhemmings/Edge-Image-Cache-Utility#4]
Notify the user if multiple GUIDs are detected in the cache path and provide instructions for correcting the setup. Similarly, check for nested GUIDs.

In both cases, offer to merge into one directory or delete/archive offenders?

**Comment by bniewo** [comment]
This is uneccesary as the end user with multiple GUIDs most likely has multiple DBs they access.

**Comment by bniewo** [comment]
Closed prematurely, Multiple GUIDs is not an issue but nested GUIDs are so check for nested GUIDs and either notify the user of the nested GUIDs or offer an option to merge the GUIDS and delete the nested item.

**Comment by nhemmings** [comment]
I'm thinking both. 

1. Throw a dialog box on screen notifying the user if at least one nested GUID folder exists. Instruct them to take the time to verify the entire office's image cache setup (direct them to the datacenter dashboard). Prompt them with talking points about (a) wasting space, (b) not functioning consistently or optimally, and (c) wasting interweb data.

2. Provide an interface for merging everything into the top level GUID, deleting duplicated files and ultimately the entire nested directory. Report how much space was cleared. The interface may be as simple as two buttons for "Do It" and "Cancel".

**Comment by bniewo** [comment]
Do we want this to tie into the Fix 0 KB files and the delete old files? 
Otherwise, we could have it be its own tab item. Maybe someone is wanting to fix a nested cache with the utility and the other two items are not an issue or is this just icing on the cake and not its own separate function of the utility?

**Comment by bniewo** [comment]
Fuck it I don't care that much. I have the functionality to fix nested caches tied to the delete 0kb and the delete old items functions buttons with a checkbox. We can revisit this at a later time if we want to change how it works.
